"""Contracts module — vendor-free interfaces and dev-time dataclasses."""

from devhub_core.contracts.node_interface import (
    CoachingResponse,
    CoachingSignal,
    DeveloperPhase,
    DeveloperProfile,
    FullHealthReport,
    HealthCheckResult,
    HealthFinding,
    HealthStatus,
    NodeDocStatus,
    NodeHealth,
    NodeInterface,
    NodeReport,
    ReviewContext,
    Severity,
    TestResult,
)
from devhub_core.contracts.dev_contracts import (
    DevTaskRequest,
    DevTaskResult,
    DocGenRequest,
    QAReport,
)
from devhub_core.contracts.growth_contracts import (
    DevelopmentChallenge,
    GrowthReport,
    LearningRecommendation,
    SkillDomain,
    SkillRadarProfile,
)
from devhub_core.contracts.research_contracts import (
    ResearchDepth,
    ResearchQueue,
    ResearchRequest,
    ResearchResponse,
    ResearchStatus,
)
from devhub_core.contracts.curator_contracts import (
    CurationFinding,
    CurationReport,
    CurationVerdict,
    KnowledgeArticle,
    KnowledgeDomain,
    KnowledgeHealthReport,
    Observation,
    ObservationType,
)

__all__ = [
    "CoachingResponse",
    "CoachingSignal",
    "DeveloperPhase",
    "DeveloperProfile",
    "FullHealthReport",
    "HealthCheckResult",
    "HealthFinding",
    "HealthStatus",
    "NodeHealth",
    "NodeDocStatus",
    "NodeReport",
    "NodeInterface",
    "ReviewContext",
    "Severity",
    "TestResult",
    "DevTaskRequest",
    "DevTaskResult",
    "DocGenRequest",
    "QAReport",
    "DevelopmentChallenge",
    "GrowthReport",
    "LearningRecommendation",
    "SkillDomain",
    "SkillRadarProfile",
    "ResearchDepth",
    "ResearchQueue",
    "ResearchRequest",
    "ResearchResponse",
    "ResearchStatus",
    "CurationFinding",
    "CurationReport",
    "CurationVerdict",
    "KnowledgeArticle",
    "KnowledgeDomain",
    "KnowledgeHealthReport",
    "Observation",
    "ObservationType",
]
